# Generated by Django 3.1.4 on 2021-01-13 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='addresses',
        ),
        migrations.AlterModelTable(
            name='card',
            table='cards',
        ),
        migrations.AlterModelTable(
            name='point',
            table='points',
        ),
    ]
