# Generated by Django 3.1.4 on 2021-01-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210113_0506'),
        ('user', '0002_auto_20210113_0143'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wish_list',
            new_name='WishList',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userId',
            new_name='account',
        ),
        migrations.RemoveField(
            model_name='card',
            name='expire_date',
        ),
        migrations.AddField(
            model_name='card',
            name='expired_month',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='card',
            name='expired_year',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='address',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='point',
            name='point',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.DeleteModel(
            name='Personal_question',
        ),
    ]
