# Generated by Django 3.1.4 on 2021-01-13 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210113_0506'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delivery_cost',
            new_name='DeliveryCost',
        ),
        migrations.RenameModel(
            old_name='Delivery_type',
            new_name='DeliveryType',
        ),
        migrations.RenameModel(
            old_name='Order_item',
            new_name='OrderItem',
        ),
        migrations.RenameModel(
            old_name='Order_state',
            new_name='OrderState',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_info',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_type',
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(max_length=200, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=45)),
                ('payment_type', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'db_table': 'order_infos',
            },
        ),
    ]
